[project]
name = "personal-finance"
version = "0.1.0"
description = "Project containing small tasks related to personal finance."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "nbformat>=5.10.4",
    "pandas>=2.2.3",
    "plotly>=5.24.1",
]
